name: GitHub App

on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - env:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "${{ secrets.APP_ID }}"
          echo "${{ secrets.PRIVATE_KEY }}"

      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}

          # Optional.
          # github_api_url: https://api.example.com

          # Optional.
          # installation_retrieval_mode: id

          # Optional.
          # installation_retrieval_payload: 1337

          # Optional.
          # Using a YAML multiline string to avoid escaping the JSON quotes.
          # permissions: >-
          #   {"pull_requests": "read"}

          private_key: ${{ secrets.PRIVATE_KEY }}

          # Optional.
          # repositories: >-
          #   ["actions/toolkit", "github/docs"]

          # Optional.
          # revoke: false

      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
      - run: echo ${{ steps.create_token.outputs.token }}


